name: mobilevit-track
channels:
  - conda-forge
  - defaults
dependencies:
  - gmp==6.2.1=h58526e2_0
  - libffi==3.4.2=h7f98852_5
  - bzip2==1.0.8=h7f98852_4
  - mkl==2021.4.0=h06a4308_640
  - torchvision==0.13.0=py37_cu113
  - lerc==3.0=h9c3ff4c_0
  - cycler==0.11.0=pyhd8ed1ab_0
  - libunistring==0.9.10=h7f98852_0
  - mkl_fft==1.3.1=py37h3e078e5_1
  - libwebp==1.2.4=h11a3e52_1
  - tk==8.6.12=h1ccaba5_0
  - ld_impl_linux-64==2.38=h1181459_1
  - libiconv==1.16=h516909a_0
  - gettext==0.19.8.1=h73d1719_1008
  - pysocks==1.7.1=py37h89c1867_5
  - openh264==2.1.1=h780b84a_0
  - libidn2==2.3.2=h7f98852_0
  - intel-openmp==2021.4.0=h06a4308_3561
  - mkl-service==2.4.0=py37h402132d_0
  - openssl==1.1.1u=h7f8727e_0
  - ncurses==6.4=h6a678d5_0
  - numpy==1.21.6=py37h976b520_0
  - cffi==1.15.1=py37h5eee18b_3
  - lcms2==2.12=h3be6417_0
  - urllib3==1.26.14=pyhd8ed1ab_0
  - zstd==1.5.2=ha4553b6_0
  - pytorch-mutex==1.0=cuda
  - libstdcxx-ng==11.2.0=he4da1e4_16
  - brotlipy==0.7.0=py37h540881e_1004
  - giflib==5.2.1=h36c2ea0_2
  - certifi==2022.12.7=pyhd8ed1ab_0
  - pycparser==2.21=pyhd8ed1ab_0
  - _openmp_mutex==5.1=1_gnu
  - libblas==3.9.0=12_linux64_mkl
  - mkl_random==1.2.2=py37h219a48f_0
  - ffmpeg==4.3=hf484d3e_0
  - tqdm==4.64.1=pyhd8ed1ab_0
  - ca-certificates==2023.5.7=hbcca054_0
  - libgcc-ng==11.2.0=h1234567_1
  - kiwisolver==1.4.4=py37h6a678d5_0
  - lz4-c==1.9.4=h6a678d5_1
  - sqlite==3.40.1=h5082296_0
  - libcblas==3.9.0=12_linux64_mkl
  - python-dateutil==2.8.2=pyhd8ed1ab_0
  - six==1.16.0=pyh6c4a22f_0
  - libtasn1==4.16.0=h27cfd23_0
  - colorama==0.4.6=pyhd8ed1ab_0
  - blas==1.0=mkl
  - pip==22.3.1=pyhd8ed1ab_0
  - zlib==1.2.13=h5eee18b_1
  - idna==3.4=pyhd8ed1ab_0
  - libwebp-base==1.2.4=h5eee18b_1
  - libdeflate==1.17=h5eee18b_1
  - jpeg==9e=h166bdaf_1
  - libtiff==4.5.0=h6a678d5_2
  - freetype==2.12.1=h4a9f257_0
  - charset-normalizer==2.0.4=pyhd8ed1ab_0
  - lame==3.100=h7f98852_1001
  - wheel==0.38.4=pyhd8ed1ab_0
  - liblapack==3.9.0=12_linux64_mkl
  - _libgcc_mutex==0.1=main
  - pytorch==1.12.0=py3.7_cuda11.3_cudnn8.3.2_0
  - cudatoolkit==11.3.1=h9edb442_10
  - readline==8.2=h5eee18b_0
  - cryptography==39.0.1=py37h9ce1e76_0
  - libgomp==11.2.0=h1234567_1
  - python_abi==3.7=2_cp37m
  - icu==67.1=he1b5a44_0
  - flit-core==3.6.0=pyhd8ed1ab_0
  - xz==5.2.10=h5eee18b_1
  - libpng==1.6.37=h21135ba_2
  - requests==2.28.1=pyhd8ed1ab_1
  - typing_extensions==4.4.0=pyha770c72_0
  - pyopenssl==23.0.0=pyhd8ed1ab_0
  - python==3.7.16=h7a1cb2a_0
  - pillow==9.4.0=py37h6a678d5_0
  - nettle==3.7.3=hbbd107a_1
  - gnutls==3.6.15=he1e5248_0
